version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  dotnetapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
